### ISSUE TITLE
Suggest Function?

### ISSUE THREAD

**Issue by svenkuegler** [acbarbosa1964/acb-bootstrap-snippets#1]
Is there a Plan to add a hint/suggest function? Because the list of available snippets is very long. 
It would be very helpfull to keep the Overview!

By the way - Thanks for the great Plugin. I love it allready.

Greetings Sven

---

Hi Sven,

Already done. I hope you have updated to the latest version.

**Comment by pth0rn** [comment]
Conflicts with Emmet extension. Using bs3+tab will not work with Emmet enabled. The popup still works and those can be used with Enter, but since the plain "bs3" isn't in the popup, it won't work since Emmet takes over the tab key.

---

Now you can use **DOWN** key or **TAB** key after "bs3" commands.
New command "bs3template" to get the "Minimum Bootstrap Template" (just like bs3).

**Comment by acbarbosa1964** [comment]
Now you can use DOWN key or TAB key after "bs3" commands.
New command "bs3template" to get the "Minimum Bootstrap Template" (just like bs3).
